# Use an official Python runtime as a base image
FROM python:3.12

# Set the working directory to /app
WORKDIR /app

# Install nophp
RUN python3 -m pip install --upgrade pip nophp 

# Copy the current directory contents into the container at /app
COPY nophp /app

# Set up Python environment
CMD ["python3", "-m", "nophp", "config/wool.yaml", "-o", "0.0.0.0", "-p", "8081"]
